# Generated by Django 3.0.8 on 2020-07-29 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_reviewed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='reviewed_by',
            new_name='user',
        ),
    ]
